# bridge and friends
PREFERRED_PROVIDER_virtual/dspbridge-module =	"linux-beagle"
PREFERRED_VERSION_tidspbridge-lib =		"git"
PREFERRED_VERSION_tidspbridge-extra =		"0.1"

# openmax
#PREFERRED_PROVIDER_virtual/openmax-il =	"meta-tiopenmax-modular"
PREFERRED_PROVIDER_virtual/openmax-il =		"tiopenmax"
PREFERRED_VERSION_tiopenmax =			"0.3.5"

# gstreamer
PREFERRED_VERSION_libgoo =			"5.16-os"
PREFERRED_VERSION_gst-goo =			"5.16"
PREFERRED_VERSION_gst-pyapps =			"5.11"
